api/urls.py
from django.urls import path
from api.views import (
    ProjectDetailView, ProjectUpdateView, ProjectDeleteView,
    TaskDetailView, TaskUpdateView, TaskDeleteView
    )


urlpatterns = [
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_api'),
    path('projects/update/<int:pk>/', ProjectUpdateView.as_view(), name='project_api_update'),
    path('projects/delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_api_delete'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_api'),
    path('tasks/update/<int:pk>/', TaskUpdateView.as_view(), name='task_api_update'),
    path('tasks/delete/<int:pk>/', TaskDeleteView.as_view(), name='task_api_delete')
]

issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from issue_tracker import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.db.models.deletion import get_candidate_relations_to_delete
from django.contrib.auth import get_user_model


class CustomModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class Types(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.name}"


class Statuses(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.name}"


class Projects(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    users = models.ManyToManyField(get_user_model(), related_name='projects', blank=True)
    description = models.TextField(max_length=2000, null=False, blank=False)
    start_date = models.DateField(null=False, blank=True)
    end_date = models.DateField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        delete_candidates = get_candidate_relations_to_delete(self.__class__._meta)
        if delete_candidates:
            for rel in delete_candidates:
                if rel.on_delete.__name__ == 'CASCADE' and rel.one_to_many and not rel.hidden:
                    for item in getattr(self, rel.related_name).all():
                        item.delete()
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f'{self.name}'


class Tasks(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='tasks', verbose_name='Исполнитель')
    summary = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=2000, null=True, blank=False)
    project = models.ForeignKey('webapp.Projects', on_delete=models.CASCADE, default='1', related_name='project')
    status = models.ForeignKey(Statuses, on_delete=models.PROTECT)
    types = models.ManyToManyField('webapp.Types', related_name='tasks', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_deleted = models.BooleanField(default=False)

    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f"{self.summary}"

templates/common/delete_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Удаление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы действительно хотите удалить обьект ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <form action="{% if deleted_object == project %} {% url 'project_delete' deleted_object.pk %} {% else %} {% url 'delete' deleted_object.pk %} {% endif %} " method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Потвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/common/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'projects' %}">Главная</a>
        <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {%  if perms.webapp.add_projects %}
                    <li class="nav-item">
                        <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'create_project' %}"
                        >Создать проект</a
                        >
                    </li>
                {% endif %}
                {%  if perms.auth.view_user %}
                    <li class="nav-item">
                        <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'users' %}"
                        >Разработчики</a
                        >
                    </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'login' %}"
                        >Войти</a
                        >
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'profile' request.user.pk %}"
                        >Привет, {{ user.get_full_name }}</a
                        >
                    </li>
                    <li class="nav-item">
                        <a
                                class="nav-link active"
                                aria-current="page"
                                href="{% url 'logout' %}"
                        >Выйти</a
                        >
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex" method="get">
                <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="search" value="{{ form.search.value|default:'' }}">
                <button class="btn btn-outline-success" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>