api/urls.py
from django.urls import path
from api.views import (
    ProjectDetailView, ProjectUpdateView, ProjectDeleteView,
    TaskDetailView, TaskUpdateView, TaskDeleteView
    )


urlpatterns = [
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_api'),
    path('projects/update/<int:pk>/', ProjectUpdateView.as_view(), name='project_api_update'),
    path('projects/delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_api_delete'),
    path('tasks/<int:pk>/', TaskDetailView.as_view(), name='task_api'),
    path('tasks/update/<int:pk>/', TaskUpdateView.as_view(), name='task_api_update'),
    path('tasks/delete/<int:pk>/', TaskDeleteView.as_view(), name='task_api_delete')
]

issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from issue_tracker import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.db.models.deletion import get_candidate_relations_to_delete
from django.contrib.auth import get_user_model


class CustomModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class Types(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.name}"


class Statuses(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return f"{self.name}"


class Projects(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    users = models.ManyToManyField(get_user_model(), related_name='projects', blank=True)
    description = models.TextField(max_length=2000, null=False, blank=False)
    start_date = models.DateField(null=False, blank=True)
    end_date = models.DateField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        delete_candidates = get_candidate_relations_to_delete(self.__class__._meta)
        if delete_candidates:
            for rel in delete_candidates:
                if rel.on_delete.__name__ == 'CASCADE' and rel.one_to_many and not rel.hidden:
                    for item in getattr(self, rel.related_name).all():
                        item.delete()
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f'{self.name}'


class Tasks(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='tasks', verbose_name='Исполнитель')
    summary = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(max_length=2000, null=True, blank=False)
    project = models.ForeignKey('webapp.Projects', on_delete=models.CASCADE, default='1', related_name='project')
    status = models.ForeignKey(Statuses, on_delete=models.PROTECT)
    types = models.ManyToManyField('webapp.Types', related_name='tasks', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_deleted = models.BooleanField(default=False)

    objects = CustomModelManager()

    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.save(update_fields=['is_deleted', ])

    def __str__(self):
        return f"{self.summary}"

webapp/views/task_views.py
from django.views.generic import (
    TemplateView, DeleteView
)
from webapp.models import Tasks, Projects
from django.shortcuts import get_object_or_404, reverse
from webapp.forms import SimpleSearchForm
from webapp.helpers import SearchView
from django.contrib.auth.mixins import PermissionRequiredMixin


class TasksView(SearchView):
    template_name = 'tasks/tasks.html'
    context_object_name = 'tasks'
    model = Tasks
    ordering = ['-created_at']
    paginate_by = 10
    search_form = SimpleSearchForm
    search_fields = {
        'summary': 'icontains',
        'description': 'icontains'
    }


class Task(PermissionRequiredMixin, TemplateView):
    template_name = 'tasks/task_page.html'
    permission_required = 'webapp.view_tasks'
    extra_context = None

    def has_permission(self):
        task = get_object_or_404(Tasks, pk=self.kwargs.get('pk'))
        project = get_object_or_404(Projects, pk=task.project_id)
        return super().has_permission() and self.request.user in project.users.all()

    def get_context_data(self, **kwargs):
        task = get_object_or_404(Tasks, pk=kwargs.get('pk'))
        project = get_object_or_404(Projects, pk=task.project_id)
        self.extra_context = {'project': project}
        kwargs['task'] = task
        return super().get_context_data(**kwargs)


class DeleteTaskView(PermissionRequiredMixin, DeleteView):
    template_name = 'tasks/task_page.html'
    model = Tasks
    permission_required = 'webapp.delete_tasks'

    def has_permission(self):
        task = get_object_or_404(Tasks, pk=self.kwargs.get('pk'))
        project = get_object_or_404(Projects, pk=task.project_id)
        return super().has_permission() and self.request.user in project.users.all()

    def get(self, request, *args, **kwargs):
        return self.delete(request=request)

    def get_success_url(self):
        return reverse('project_detail', kwargs={'pk': self.get_object().project_id})

templates/tasks/task_page.html
{% extends 'base.html' %} {% block content %}
    <div class="boxes">
        <div class="box">
            <p class="col-3">Зоголовок:</p>
            <p class="col-9">{{ task.summary }}</p>
        </div>
        <div class="box">
            <p class="col-3">Описание:</p>
            <p class="col-9">{{ task.description }}</p>
        </div>
        <div class="box">
            <p class="col-3">Статус:</p>
            <p class="col-9">{{ task.status }}</p>
        </div>
        <div class="box">
            <p class="col-3">Проект:</p>
            <p class="col-9">{{ task.project }}</p>
        </div>
        <div class="box">
            <p class="col-3">Тип:</p>
            {% for types in task.types.all %}
                {{ types }}
            {% endfor %}
        </div>
        <div class="box">
            <p class="col-3">Время создания:</p>
            <p class="col-9">{{ task.created_at| date:'Y-m-d' }}</p>
        </div>
        <div class="box">
            <p class="col-3">Последнее изменение:</p>
            <p class="col-9">{{ task.updated_at| date:'Y-m-d' }}</p>
        </div>
        <div class="button_edit">
            {% if perms.webapp.delete_tasks and user in project.users.all %}
                <button data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-danger">Удалить</button>
            {% endif %}
            {% if perms.webapp.change_tasks and user in project.users.all %}
                <a class="btn btn-primary" href="{% url 'task_update' task.pk %}" role="button">Изменить</a>
            {% endif %}
        </div>
    </div>
    {% include 'common/delete_modal.html' with deleted_object=task %}
{% endblock %}

templates/tasks/tasks.html
{% extends 'base.html' %} {% block content %}
    <h1 class="title">Задачи</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Исполнитель</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Статус</th>
            <th scope="col">Проект</th>
            <th scope="col">Дата создания</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td><a href="{% url 'profile' request.user.pk %}" class="task">{{ task.user.get_full_name }}</a></td>
                <td><a href="{% url 'task_page' task.pk %}" class="task">{{ task.summary }}</a></td>
                <td>{{ task.status }}</td>
                <td>{{ task.project }}</td>
                <td>{{ task.created_at| date:'Y-m-d'}}</td>
            </tr>
        {% empty %}
        <h3 style="text-align: center">Задачи не найдены</h3>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        {% include 'partial/tasks/pagination.html' %}
    {% endif %}
{% endblock %}